version: '3.7'

networks:
  localdev:
    name: localdev

services:
  wearther-frontend:
    container_name: 'weather-frontend'
    build: './WeatherForecast.UI'
    ports:
      - 8080:80
    networks:
      - localdev

  weatherforecast:
    build: './'
    ports:
      - "7070:8080"
    networks:
      - localdev
